
	Move.l	Showbuffer,Src
	Addi.l	#40*110,Src
	Move.l	Currbuffer,Dest
	Addi.l	#40*110,Dest

	BLIT	Src,Dest,#$814,#0,#0,#1,#$FFFF,#$FFFF
	
	Addi.l	#10240,Src
	Addi.l	#10240,Dest
	BLIT	Src,Dest,#$814,#0,#0,#1,#$FFFF,#$FFFF

	Addi.l	#10240,Src
	Addi.l	#10240,Dest
	BLIT	Src,Dest,#$814,#0,#0,#1,#$FFFF,#$FFFF

	Addi.l	#10240,Src
	Addi.l	#10240,Dest
	BLIT	Src,Dest,#$814,#0,#0,#1,#$FFFF,#$FFFF

	Move.l	Showbuffer,Src
	Addi.l	#40*142,Src
	Move.l	Currbuffer,Dest
	Addi.l	#40*142,Dest

	BLIT	Src,Dest,#$214,#0,#0,#2,#$FFFF,#$FFFF
	
	Addi.l	#10240,Src
	Addi.l	#10240,Dest
	BLIT	Src,Dest,#$214,#0,#0,#2,#$FFFF,#$FFFF

	Addi.l	#10240,Src
	Addi.l	#10240,Dest
	BLIT	Src,Dest,#$214,#0,#0,#2,#$FFFF,#$FFFF

	Addi.l	#10240,Src
	Addi.l	#10240,Dest
	BLIT	Src,Dest,#$214,#0,#0,#2,#$FFFF,#$FFFF

	Move.l	Showbuffer,Src
	Addi.l	#40*150,Src
	Move.l	Currbuffer,Dest
	Addi.l	#40*150,Dest

	BLIT	Src,Dest,#$154,#0,#0,#3,#$FFFF,#$FFFF
	
	Addi.l	#10240,Src
	Addi.l	#10240,Dest
	BLIT	Src,Dest,#$154,#0,#0,#3,#$FFFF,#$FFFF

	Addi.l	#10240,Src
	Addi.l	#10240,Dest
	BLIT	Src,Dest,#$154,#0,#0,#3,#$FFFF,#$FFFF

	Addi.l	#10240,Src
	Addi.l	#10240,Dest
	BLIT	Src,Dest,#$154,#0,#0,#3,#$FFFF,#$FFFF

	Move.l	Showbuffer,Src
	Addi.l	#40*155,Src
	Move.l	Currbuffer,Dest
	Addi.l	#40*155,Dest

	BLIT	Src,Dest,#$294,#0,#0,#4,#$FFFF,#$FFFF
	
	Addi.l	#10240,Src
	Addi.l	#10240,Dest
	BLIT	Src,Dest,#$294,#0,#0,#4,#$FFFF,#$FFFF

	Addi.l	#10240,Src
	Addi.l	#10240,Dest
	BLIT	Src,Dest,#$294,#0,#0,#4,#$FFFF,#$FFFF

	Addi.l	#10240,Src
	Addi.l	#10240,Dest
	BLIT	Src,Dest,#$294,#0,#0,#4,#$FFFF,#$FFFF

	Move.l	Showbuffer,Src
	Addi.l	#40*165,Src
	Move.l	Currbuffer,Dest
	Addi.l	#40*165,Dest

	BLIT	Src,Dest,#$294,#0,#0,#5,#$FFFF,#$FFFF
	
	Addi.l	#10240,Src
	Addi.l	#10240,Dest
	BLIT	Src,Dest,#$294,#0,#0,#5,#$FFFF,#$FFFF

	Addi.l	#10240,Src
	Addi.l	#10240,Dest
	BLIT	Src,Dest,#$294,#0,#0,#5,#$FFFF,#$FFFF

	Addi.l	#10240,Src
	Addi.l	#10240,Dest
	BLIT	Src,Dest,#$294,#0,#0,#5,#$FFFF,#$FFFF

	Move.l	Showbuffer,Src
	Addi.l	#40*175,Src
	Move.l	Currbuffer,Dest
	Addi.l	#40*175,Dest

	BLIT	Src,Dest,#$294,#0,#0,#6,#$FFFF,#$FFFF
	
	Addi.l	#10240,Src
	Addi.l	#10240,Dest
	BLIT	Src,Dest,#$294,#0,#0,#6,#$FFFF,#$FFFF

	Addi.l	#10240,Src
	Addi.l	#10240,Dest
	BLIT	Src,Dest,#$294,#0,#0,#6,#$FFFF,#$FFFF

	Addi.l	#10240,Src
	Addi.l	#10240,Dest
	BLIT	Src,Dest,#$294,#0,#0,#6,#$FFFF,#$FFFF

	Move.l	Showbuffer,Src
	Addi.l	#40*185,Src
	Move.l	Currbuffer,Dest
	Addi.l	#40*185,Dest

	BLIT	Src,Dest,#$294,#0,#0,#7,#$FFFF,#$FFFF
	
	Addi.l	#10240,Src
	Addi.l	#10240,Dest
	BLIT	Src,Dest,#$294,#0,#0,#7,#$FFFF,#$FFFF

	Addi.l	#10240,Src
	Addi.l	#10240,Dest
	BLIT	Src,Dest,#$294,#0,#0,#7,#$FFFF,#$FFFF

	Addi.l	#10240,Src
	Addi.l	#10240,Dest
	BLIT	Src,Dest,#$294,#0,#0,#7,#$FFFF,#$FFFF

	Move.l	Showbuffer,Src
	Addi.l	#40*195,Src
	Move.l	Currbuffer,Dest
	Addi.l	#40*195,Dest

	BLIT	Src,Dest,#$A14,#0,#0,#10,#$FFFF,#$FFFF
	
	Addi.l	#10240,Src
	Addi.l	#10240,Dest
	BLIT	Src,Dest,#$A14,#0,#0,#10,#$FFFF,#$FFFF

	Addi.l	#10240,Src
	Addi.l	#10240,Dest
	BLIT	Src,Dest,#$A14,#0,#0,#10,#$FFFF,#$FFFF

	Addi.l	#10240,Src
	Addi.l	#10240,Dest
	BLIT	Src,Dest,#$A14,#0,#0,#10,#$FFFF,#$FFFF

	*************
	*   Part 2  *
	*************

	Move.l	Showbuffer,Src
	Addi.l	#40*110,Src
	Addi.l	#38,Src
	Move.l	Currbuffer,Dest
	Addi.l	#40*110,Dest

	BLIT	Src,Dest,#$801,#38,#38,#15,#$FFFF,#$FFFF
	
	Addi.l	#10240,Src
	Addi.l	#10240,Dest
	BLIT	Src,Dest,#$801,#38,#38,#15,#$FFFF,#$FFFF

	Addi.l	#10240,Src
	Addi.l	#10240,Dest
	BLIT	Src,Dest,#$801,#38,#38,#15,#$FFFF,#$FFFF

	Addi.l	#10240,Src
	Addi.l	#10240,Dest
	BLIT	Src,Dest,#$801,#38,#38,#15,#$FFFF,#$FFFF

	Move.l	Showbuffer,Src
	Addi.l	#40*142,Src
	Addi.l	#38,Src
	Move.l	Currbuffer,Dest
	Addi.l	#40*142,Dest

	BLIT	Src,Dest,#$201,#38,#38,#14,#$FFFF,#$FFFF
	
	Addi.l	#10240,Src
	Addi.l	#10240,Dest
	BLIT	Src,Dest,#$201,#38,#38,#14,#$FFFF,#$FFFF

	Addi.l	#10240,Src
	Addi.l	#10240,Dest
	BLIT	Src,Dest,#$201,#38,#38,#14,#$FFFF,#$FFFF

	Addi.l	#10240,Src
	Addi.l	#10240,Dest
	BLIT	Src,Dest,#$201,#38,#38,#14,#$FFFF,#$FFFF

	Move.l	Showbuffer,Src
	Addi.l	#40*150,Src
	Addi.l	#38,Src
	Move.l	Currbuffer,Dest
	Addi.l	#40*150,Dest

	BLIT	Src,Dest,#$141,#38,#38,#13,#$FFFF,#$FFFF
	
	Addi.l	#10240,Src
	Addi.l	#10240,Dest
	BLIT	Src,Dest,#$141,#38,#38,#13,#$FFFF,#$FFFF

	Addi.l	#10240,Src
	Addi.l	#10240,Dest
	BLIT	Src,Dest,#$141,#38,#38,#13,#$FFFF,#$FFFF

	Addi.l	#10240,Src
	Addi.l	#10240,Dest
	BLIT	Src,Dest,#$141,#38,#38,#13,#$FFFF,#$FFFF

	Move.l	Showbuffer,Src
	Addi.l	#40*155,Src
	Addi.l	#38,Src
	Move.l	Currbuffer,Dest
	Addi.l	#40*155,Dest

	BLIT	Src,Dest,#$281,#38,#38,#12,#$FFFF,#$FFFF
	
	Addi.l	#10240,Src
	Addi.l	#10240,Dest
	BLIT	Src,Dest,#$281,#38,#38,#12,#$FFFF,#$FFFF

	Addi.l	#10240,Src
	Addi.l	#10240,Dest
	BLIT	Src,Dest,#$281,#38,#38,#12,#$FFFF,#$FFFF

	Addi.l	#10240,Src
	Addi.l	#10240,Dest
	BLIT	Src,Dest,#$281,#38,#38,#12,#$FFFF,#$FFFF

	Move.l	Showbuffer,Src
	Addi.l	#40*165,Src
	Addi.l	#38,Src
	Move.l	Currbuffer,Dest
	Addi.l	#40*165,Dest

	BLIT	Src,Dest,#$281,#38,#38,#11,#$FFFF,#$FFFF
	
	Addi.l	#10240,Src
	Addi.l	#10240,Dest
	BLIT	Src,Dest,#$281,#38,#38,#11,#$FFFF,#$FFFF

	Addi.l	#10240,Src
	Addi.l	#10240,Dest
	BLIT	Src,Dest,#$281,#38,#38,#11,#$FFFF,#$FFFF

	Addi.l	#10240,Src
	Addi.l	#10240,Dest
	BLIT	Src,Dest,#$281,#38,#38,#11,#$FFFF,#$FFFF

	Move.l	Showbuffer,Src
	Addi.l	#40*175,Src
	Addi.l	#38,Src
	Move.l	Currbuffer,Dest
	Addi.l	#40*175,Dest

	BLIT	Src,Dest,#$281,#38,#38,#10,#$FFFF,#$FFFF
	
	Addi.l	#10240,Src
	Addi.l	#10240,Dest
	BLIT	Src,Dest,#$281,#38,#38,#10,#$FFFF,#$FFFF

	Addi.l	#10240,Src
	Addi.l	#10240,Dest
	BLIT	Src,Dest,#$281,#38,#38,#10,#$FFFF,#$FFFF

	Addi.l	#10240,Src
	Addi.l	#10240,Dest
	BLIT	Src,Dest,#$281,#38,#38,#10,#$FFFF,#$FFFF

	Move.l	Showbuffer,Src
	Addi.l	#40*185,Src
	Addi.l	#38,Src
	Move.l	Currbuffer,Dest
	Addi.l	#40*185,Dest

	BLIT	Src,Dest,#$281,#38,#38,#9,#$FFFF,#$FFFF
	
	Addi.l	#10240,Src
	Addi.l	#10240,Dest
	BLIT	Src,Dest,#$281,#38,#38,#9,#$FFFF,#$FFFF

	Addi.l	#10240,Src
	Addi.l	#10240,Dest
	BLIT	Src,Dest,#$281,#38,#38,#9,#$FFFF,#$FFFF

	Addi.l	#10240,Src
	Addi.l	#10240,Dest
	BLIT	Src,Dest,#$281,#38,#38,#9,#$FFFF,#$FFFF

	Move.l	Showbuffer,Src
	Addi.l	#40*195,Src
	Addi.l	#38,Src
	Move.l	Currbuffer,Dest
	Addi.l	#40*195,Dest

	BLIT	Src,Dest,#$A01,#38,#38,#5,#$FFFF,#$FFFF
	
	Addi.l	#10240,Src
	Addi.l	#10240,Dest
	BLIT	Src,Dest,#$A01,#38,#38,#5,#$FFFF,#$FFFF

	Addi.l	#10240,Src
	Addi.l	#10240,Dest
	BLIT	Src,Dest,#$A01,#38,#38,#5,#$FFFF,#$FFFF

	Addi.l	#10240,Src
	Addi.l	#10240,Dest
	BLIT	Src,Dest,#$A01,#38,#38,#5,#$FFFF,#$FFFF
